on:
    workflow_call:
      inputs:
        config-path:
          required: true
          type: string
      secrets:
        envPAT:
          required: true
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Checkout to latest release tag
        run: |
            git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Install Dependencies
        run: npm install
      - name: Generate .env file
        run: cp .env.example .env
      - name: Build
        run: npm run build
      - name: Install Firebase
        run: npm install -g firebase-tools
      - name: Set Firebase project
        run: firebase use default --token "$HOTWAX_PUBLIC_SECRET"
        env:
            HOTWAX_PUBLIC_SECRET: ${{ secrets.HOTWAX_PUBLIC_SECRET }}
      - name: Deploy
        run: firebase deploy --token "$HOTWAX_PUBLIC_SECRET" -m "Deploying via GitHub actions"  --only hosting:uat
        env:
            HOTWAX_PUBLIC_SECRET: ${{ secrets.HOTWAX_PUBLIC_SECRET }}